services:
  clinicapp.webapi:
    image: ${DOCKER_REGISTRY-}clinicappwebapi
    build:
      context: .
      dockerfile: ClinicApp.WebApi/Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"
  clinicapp.database:
    image: mcr.microsoft.com/mssql/server:2025-latest
    environment: 
      - "ACCEPT_EULA=Y"
      - "MSSQL_SA_PASSWORD=Passw0rd!"
      - "MSSQL_PID=Express"
    ports:
      - "4000:1433"
  clinicapp.frontend:
    image: ${DOCKER_REGISTRY-}clinicappfrontend
    build:
      context: ../clinicapp-front
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
